name: clang-format-check
on:
    push:

jobs:
  build:
    name: clang-format-check
    runs-on: ubuntu-18.04
    steps:
        - name: Fetch repository
          uses: actions/checkout@v1
        - name: Configure
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron
          run: |
              mkdir BUILD && cd BUILD
              cmake -DCORENRN_CLANG_FORMAT=ON -DCORENRN_ENABLE_MPI=OFF -DCORENRN_ENABLE_OPENMP=OFF ..
        - name: Run clang-format
          shell: bash
          working-directory: ${{runner.workspace}}/CoreNeuron/BUILD
          run: make check-clang-format
        - uses: mxschmitt/action-tmate@v3
